version: "3.9"

services:
  feDev:
    container_name: filippi_fe_dev
    image: filippi_fe_dev:1.0.0
    build:
      context: ./fe
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./fe/src:/usr/src/fe/src
      - ./fe/common:/usr/src/fe/common
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.9
    networks:
      - app-net
    restart: unless-stopped

  devServer:
    container_name: filippi_be_dev
    image: filippi_be_dev:1.0.0
    build:
      context: ./be
      target: development
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-net
    volumes:
      - ./be/src:/usr/src/be/src
    restart: unless-stopped

networks:
  app-net: